version: '2.4'

services:
  frontend-dev:
    # build:
    #   context: ./frontend
    # user: "${UID}:${GID}"
    user: "1000:1000"
    image: node:16.3.0-alpine3.13
    volumes:
      - ./frontend:/app
    working_dir: /app
    # command: npm install -g npm@7.19.1
    # command: id
    command: npm start
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: build.Dockerfile
    image: socnet-chat-frontend
    ports:
      - 3000:80

  backend:
    user: "1000:1000"
    image: socnet_chat_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ash -c "/wait && python app.py"
    environment:
      WAIT_HOSTS: db:3306, db_shard_1:3306, db_shard_2:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 3
      WAIT_HOST_CONNECT_TIMEOUT: 3

      FERNET_KEY: 'sIv6jBFwPkNSZP4gVUmzQUnsaMs7g1g7UMRStf5RpCM='
      DATABASE_URL: mysql://socnet:socnetpass@db:3306/socnet
      SHARDS_COUNT: 2
      SHARD_1_URL: mysql://socnet:socnetpass@db_shard_1:3306/socnet
      SHARD_2_URL: mysql://socnet:socnetpass@db_shard_2:3306/socnet

      PORT: 8080
      REST_PORT: 8081

    volumes:
      - ./backend:/app
    expose:
      - 8080
      - 8081
    # depends_on:
    #   - db
    #   - db_shard_1
    #   - db_shard_2

  db_shard_1:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socnet
      MYSQL_USER: socnet
      MYSQL_PASSWORD: socnetpass
      LANG: C.UTF-8

    ports:
      # to connect from localhost
      - 127.0.0.1:3309:3306
    volumes:
      - ./.data_db_shard_1:/var/lib/mysql
      - ./db/shard_1.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    mem_limit: 6000M

  db_shard_2:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socnet
      MYSQL_USER: socnet
      MYSQL_PASSWORD: socnetpass
      LANG: C.UTF-8

    ports:
      # to connect from localhost
      - 127.0.0.1:3310:3306
    volumes:
      - ./.data_db_shard_2:/var/lib/mysql
      - ./db/shard_2.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    mem_limit: 6000M

  db:
     extends:
      file: ../../docker-compose.yml
      service: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
